// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zovies.Backend.Context;

#nullable disable

namespace Zovies.Backend.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20220509040843_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("Zovies.Backend.Models.Cast", b =>
                {
                    b.Property<int>("CastID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MovieID")
                        .HasColumnType("INTEGER");

                    b.HasKey("CastID");

                    b.HasIndex("MovieID");

                    b.ToTable("Actors");
                });

            modelBuilder.Entity("Zovies.Backend.Models.Details", b =>
                {
                    b.Property<int>("DetailsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MovieCoverPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MovieFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Rating")
                        .HasColumnType("REAL");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetailsID");

                    b.ToTable("MovieDetails");
                });

            modelBuilder.Entity("Zovies.Backend.Models.Genre", b =>
                {
                    b.Property<int>("GenreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DetailsID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GenreID");

                    b.HasIndex("DetailsID");

                    b.ToTable("Genre");
                });

            modelBuilder.Entity("Zovies.Backend.Models.Movie", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MovieDetailsDetailsID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MovieName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MovieID");

                    b.HasIndex("MovieDetailsDetailsID");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("Zovies.Backend.Models.Cast", b =>
                {
                    b.HasOne("Zovies.Backend.Models.Movie", null)
                        .WithMany("MovieCast")
                        .HasForeignKey("MovieID");
                });

            modelBuilder.Entity("Zovies.Backend.Models.Genre", b =>
                {
                    b.HasOne("Zovies.Backend.Models.Details", null)
                        .WithMany("MovieGenres")
                        .HasForeignKey("DetailsID");
                });

            modelBuilder.Entity("Zovies.Backend.Models.Movie", b =>
                {
                    b.HasOne("Zovies.Backend.Models.Details", "MovieDetails")
                        .WithMany()
                        .HasForeignKey("MovieDetailsDetailsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MovieDetails");
                });

            modelBuilder.Entity("Zovies.Backend.Models.Details", b =>
                {
                    b.Navigation("MovieGenres");
                });

            modelBuilder.Entity("Zovies.Backend.Models.Movie", b =>
                {
                    b.Navigation("MovieCast");
                });
#pragma warning restore 612, 618
        }
    }
}
